layout_spectrum: 0.6213748
color:
  saturation: 0.490333
  brandStrength: 0.7887372
  lightness: 0.9006445
  rhythmicContrast: 0.5870032
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.6654136
name: DJ SLOW
